import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillInstagram, AiFillGithub} from 'react-icons/ai';
import selfie from '../public/selfie2.jpg';
import magic from '../public/magic-wand.png';
import responsive from '../public/responsive.png';
import seo from '../public/seo.png';
import web1 from '../public/oghdr.png';
import web2 from '../public/jreptiles.png';
import web3 from '../public/hdr1.png';
import web4 from '../public/hdr2.png';
import web5 from '../public/chippyd.png';
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return ( 
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Paige DePrizio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-indigo-100 text-gray-800 px-10 font-montserrat md:px-20 lg:px-40 dark:bg-indigo-800 dark:text-gray-200">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-montserra">paigedeprizio</h1>
            <ul className="flex items-center">
              <li>
              <BsFillMoonStarsFill  onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-gray-200"/>
                </li>
              <li><a className="bg-indigo-600 dark:bg-indigo-950 text-white px-4 py-2 rounded-md ml-8"href="#">Resume</a></li>
            </ul>
          </nav> 
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 font-medium md:text-6xl">Paige DePrizio</h2>
            <h3 className='text-2xl py-2 dark:text-gray-200 md:text-3xl'>Developer and designer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto'>Throughout my journey as a developer, I've had the 
            privilege of working on diverse projects, both remotely and in-person. My expertise encompasses a broad spectrum of services tailored to meet the unique needs 
            of each project. From creating seamless user experiences through UX design to developing robust and responsive websites, I specialize in translating ideas into 
            compelling digital solutions. I also offer Search Engine Optimization (SEO) services, ensuring your online presence is not only visually appealing but also easily 
            discoverable by your target audience. With a client-centric approach, I prioritize your satisfaction, working closely to understand your goals and requirements. My 
            passion for technology, coupled with a commitment to innovation and creativity, drives me to deliver high-quality work. Let's collaborate to transform your ideas into 
            captivating digital experiences.</p>
          </div> 
           <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-100'>

            <a href="https://www.linkedin.com/in/paige-deprizio-95322b177" target="_blank" rel="noopener noreferrer">
          <AiFillLinkedin />
          </a>
          <a href="https://www.instagram.com/paigedeprizio/" target="_blank" rel="noopener noreferrer">
         <AiFillInstagram />
         </a>
         <a href="https://github.com/pdeprizio" target="_blank" rel="noopener noreferrer">
        <AiFillGithub />
         </a>
           </div>
           
           <div>
            <Image  src={selfie} width={300} height={300} className='justify-center text-center mx-auto mt-10 rounded-lg shadow-lg'/>
           </div>
        </section>


        <section>
          <div>
            <h3 className='text-3xl py-1 mt-10 text-center dark:text-gray-200'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center'>Since the beginning of my journey as a developer, I've done remote work for.....I offer a wide range of services including UX Design, Web Development, and SEO Implementation.</p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 mx-auto dark:text-gray-200 bg-white'>
              
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-200'>Beautiful Designs</h3>
              <p className='py-2 dark:text-gray-200'>Creating elegant designs suited for your needs and built off of your dreams.</p>
              <h4 className='py-4 dark:text-gray-200'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Canva</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Figma</p>

            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-white'>
              
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-200'>Sleek Content</h3>
              <p className='py-2 dark:text-gray-200'>Creating elegant designs suited for your needs and built off of your dreams.</p>
              <h4 className='py-4 dark:text-gray-200'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Canva</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Figma</p>

            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-white'>
              
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-200'>Beautiful Designs</h3>
              <p className='py-2 dark:text-gray-200'>Creating elegant designs suited for your needs and built off of your dreams.</p>
              <h4 className='py-4 dark:text-gray-200'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Canva</p>
              <p className='text-gray-800 py-1 dark:text-gray-200'>Figma</p>

            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-200 text-center'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center'>Write content here about your time as a developer .................</p>
          </div>
         <div>
          <div>
            <Image src={web5} className='px-5 mb-5' />
          </div>
          <div>
            <Image src={web4} className='px-5 mb-5' />
          </div>
          <div>
            <Image src={web3} className='px-5 mb-5' />
          </div>
          <div>
            <Image src={web2} className='px-5 mb-5'/>
          </div>
          <div>
            <Image src={web1} className='px-5 mb-5'/>
          </div>
         </div>
        </section>
      </main>
      </div>
    </>
  )
}
